title: How I met my husband
author: Becky
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning to use github. So the first blog is short story about how I met my husband.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
